= Conclusion & Future Work <conclusion>

The main goal of this thesis was to determine whether sparse strips are a suitable approach for implementing a state-of-the-art 2D renderer. To this end, we built a CPU-based 2D renderer with the given paradigm at its core to validate that all of the expected features are compatible with the approach (some other commonly-expected features of a 2D renderer include masks and clip paths, which _are_ supported by Vello CPU but have been omitted for space reasons). In our evaluation, we concluded that, unfortunately, the renderer is unable to beat Blend2D in terms of raw performance output, in virtue of the large amount of optimization work that has been done there. Nevertheless, we do show that Vello CPU exhibits very competitive performance for small-sized shapes and eclipses nearly all other renderers, including the Google-maintained Skia library, as the size increases. We also show that this speedup is often compounded when enabling multi-threading. We therefore still consider this a notable success and conclude that the sparse strips paradigm is indeed very effective and forms a suitable basis for a performant renderer.

We now present three avenues for future work that could be explored.

First, it is worth exploring how this approach could be adapted for GPU-based rendering. While CPU-based rendering has its use cases, for most interactive rendering it is usually still preferable to make use of hardware-acceleration for better throughput. In fact, at the time of writing there is a parallel attempt to create a CPU/GPU-hybrid renderer #footnote[https://github.com/linebender/vello/tree/main/sparse_strips/vello_hybrid], where the CPU is responsible for all stages up to coarse rasterization and the final fine rasterization happens on the GPU. This current approach already works and highlights the usefulness of having a pipeline consisting of well-separated stages with self-contained intermediate representations, but there is a lot more exploration work to be done. For example, an interesting question would be to determine whether the separation can be changed so that only curve flattening happens on the CPU, while strip generation and coarse rasterization is moved to the GPU. As part of this, it might also be worthwhile to explore whether a tile size of 8x8 is more suitable for GPU-based rendering compared to the currently-used 4x4 tile size on CPU.

Next, our evaluation has shown that Vello CPU has a weakness for small geometries. We also asserted that the most-likely culprit for this behavior is the fixed 4x4 size of tiles, resulting in a lot of unnecessary computation work during strip generation. It is not easily possible to introduce variable-height strips, however, it _is_ possible to introduce variable-width strips. The way this could be achieved is by letting each tile store the horizontal extents of the containing line and then only computing winding numbers for pixel-columns that are actually covered by a line. The downside would be that future steps in the pipeline can no longer assume that the width of a strip is a multiple of four, an assumption that is at the moment baked into most of the SIMD code.

Finally, the third major point that could use more dedicated attention is multi-threading. On the one hand, this includes investigating why the speedup for parallel fine rasterization is not as high as expected. On the other hand, this requires more fundamentally exploring how coarse rasterization, which currently forms the only serial bottleneck in the pipeline, can be made more parallel. There are different approaches that could be explored, like somehow performing parts of coarse rasterization _within_ the worker, but getting it fully parallelized is non-trivial.
